# Generated by Django 3.1.3 on 2020-11-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201126_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=100)),
                ('n_of_posts', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
