# Generated by Django 3.1.3 on 2020-11-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201129_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_n', models.CharField(max_length=120)),
                ('n_of_posts', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
