# Generated by Django 3.1.3 on 2020-11-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201129_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diocane',
            new_name='Amind_page',
        ),
    ]
