# Generated by Django 3.1.3 on 2020-11-29 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201129_2254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amind_page',
            new_name='Admin_page',
        ),
    ]
