# Generated by Django 3.1.3 on 2020-11-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201129_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin_page',
            new_name='Diocane',
        ),
    ]
