# Generated by Django 3.1.3 on 2020-11-29 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201129_2258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diocane',
            new_name='Admin',
        ),
    ]
