# Generated by Django 3.1.3 on 2020-11-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201129_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='nofposts',
            new_name='n_of_posts',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='usern',
            new_name='user_n',
        ),
    ]
