# Generated by Django 3.1.3 on 2020-11-30 15:22

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201130_1020'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='admin',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
