# Generated by Django 3.1.3 on 2020-11-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201130_1622'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='admin',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='hash',
            field=models.CharField(blank=True, default=None, max_length=66, null=True),
        ),
    ]
