# Generated by Django 3.1.3 on 2020-11-30 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201130_2232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
