# Generated by Django 3.1.3 on 2020-11-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_n', models.CharField(max_length=100)),
                ('n_of_posts', models.CharField(max_length=100)),
            ],
        ),
    ]
