# Generated by Django 3.1.3 on 2020-11-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='n_of_posts',
            field=models.IntegerField(default=1, max_length=100),
        ),
    ]
