# Generated by Django 3.1.3 on 2020-11-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201130_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='n_of_posts',
            field=models.IntegerField(max_length=1),
        ),
    ]
