# Generated by Django 3.1.3 on 2020-12-01 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20201201_0029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
