# Generated by Django 3.1.3 on 2020-12-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loguser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
