# Generated by Django 3.1.3 on 2020-12-05 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loguser', '0002_auto_20201205_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ip',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
