# Generated by Django 3.1.3 on 2020-12-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loguser', '0003_auto_20201205_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
